# ======================================
# EduSmart Redis Configuration
# ======================================


# Persistance

appendonly yes


# Port

port 6379


# Nombre maximum de mémoire

maxmemory 256mb


# Politique suppression

maxmemory-policy allkeys-lru


# Logs

loglevel notice


# Sécurité

protected-mode yes